version: "3.9"

services:
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    networks:
      - agri-network

  client:
    build: ./client
    container_name: client
    ports:
      - "8000:8000"
    depends_on:
      - server
    networks:
      - agri-network

networks:
  agri-network:
    driver: bridge
